package com.gustavo.blogpessoaldeise.security;

import java.util.Collection;
import java.util.List;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import com.gustavo.blogpessoaldeise.model.Usuario;


//A CLASSE IMPLEMENTA A INTERFACE 'USERDETAILS'.
//ISSO É COMO UM "CONTRATO" QUE OBRIGA ESTA CLASSE A TER CERTOS MÉTODOS.
//O SPRING SECURITY USA ESSES MÉTODOS PADRÃO PARA OBTER OS DADOS DO USUÁRIO.
public class UserDetailsImpl implements UserDetails {

	
	//VARIAVEL PRIVADA
	//QUE SERVE PARA DEFINIR A VERSÃO DESSE SISTEMA
	//1L = O 1 É VERSÃO DESSE SISTEMA E O "L" INDICA QUE O NÚMERO É DO TIPO LONG
	private static final long serialVersionUID = 1L;

	
	
	
	//VARIAVEIS QUE GUARDA O NOME DO USUARIO E SENHA
	private String userEmail;
	private String password;
	
	//PRIVADO
	//COM UMA LISTA
	//GrantedAuthority = REPRESENTA AS PERMISSÕES QUE CADA USUARIO VAI TER (EX: PERMISSÕES DE ADMIN, USER OU MODERADOR)
	//authorities = NOME DA VARIAVEL
	//RESUMO: authorities É DO TIPO DE UMA LISTA DE PERMISSÕES, ONDE ELE GUARDA TODOS OS TIPO DE PERMISSÕES QUE UM USUARIO PODE TER
	private List<GrantedAuthority> authorities;

	
	
	
	//PEGA O LOGIN DO USUSARIO E A SENHA E GUARDA NO UserDetailsImpl
	//PARA QUE ISSO: O SPRING SECURITY PRECISA DE UM OBJETO QUE TENHA O NOME DO USUARIO, SENHA E AS PERMISSÕES
	//PARA SABER SE O USUARIO PODE ENTRAR E O QUE ELE PODE ACESSAR DEPOIS DE LOGADO
	public UserDetailsImpl(Usuario email) {
		this.userEmail = email.getEmail();
		this.password = email.getSenha();
	}

	
	
	// ESTE É O CONSTRUTOR VAZIO.
	// OBS: SUA DÚVIDA É EXCELENTE! O MOTIVO DELE EXISTIR É POR COMPATIBILIDADE.
	// ALGUMAS FERRAMENTAS DO JAVA PRECISAM DE UM CONSTRUTOR VAZIO PARA CONSEGUIR
	// CRIAR O OBJETO. MESMO QUE VOCÊ NÃO O USE DIRETAMENTE, É UMA BOA PRÁTICA MANTÊ-LO.
	public UserDetailsImpl() {	}

	
	
	
	//@OVERRIDE = ESTÁ SOBESCREVENDO UM MÉTODO QUE JÁ EXISTE
	//ESSE MÉTODO VEM DA INTERFACE UserDetails
	@Override
	//Collection = VAI GUARDAR UMA COLEÇÃO DE PERMISSÕES DO USUARIO
	//? = SIGNIFICA QUALQUER TIPO
	//MAS NÃO VAI GUARDAR QUALQUER TIPO, VAI GUARDAR QUALQUER TIPO QUE SEJA GranteAuthority	OU QUE HERDE DELA
	//getAuthorities() = NOME DO METODO
	public Collection<? extends GrantedAuthority> getAuthorities() {

		//RETORNA UMA LISTA DE PERIMISSÕES DO USUARIO (TIPO ADMIN, USER, ETC...)
		return authorities;
		
		//QUANDO CHAMA O METODO getAuthorities, ELE DEVOLVE ESSA LISTA DE PERMISSÕES QUE ESTÁ GUARDADA NA VARIAVEL authorities
	}

	
	
	
	
	
	
	// ESTE MÉTODO DO "CONTRATO" DEVOLVE A SENHA DO USUÁRIO.
	// O SPRING SECURITY VAI USAR ESTE VALOR PARA COMPARAR COM A SENHA FORNECIDA NO LOGIN.
	@Override
	public String getPassword() {

		//RETORNA O SENHA DO USUARIO QUE ESTÁ GUARDADDO NA VARIAVEL password
		return password;
	}

	
	
	// ESTE MÉTODO DO "CONTRATO" DEVOLVE O NOME DE USUÁRIO.
	// PARA O SPRING, "USERNAME" É O IDENTIFICADOR ÚNICO DO USUÁRIO. NO NOSSO CASO, É O E-MAIL.
	@Override
	public String getUsername() {

		//RETORNA O email DO USUARIO QUE ESTÁ GUARDADA NA VARIAVEL userEmail
		return userEmail;
	}

	
	
	
	
	
	
	
	
	
	// --- MÉTODOS DE STATUS DA CONTA ---
	// PARA ESTE PROJETO, TODOS RETORNAM 'TRUE', O QUE SIGNIFICA QUE AS CONTAS ESTÃO SEMPRE ATIVAS.

	
	
	@Override
	// ESSE MÉTODO SOBRESCREVE O MÉTODO DA INTERFACE UserDetails
	public boolean isAccountNonExpired() {
		
	    // AQUI VOCÊ ESTÁ DIZENDO: SEMPRE QUE PERGUNTAREM SE A CONTA NÃO ESTÁ EXPIRADA,
	    // A RESPOSTA SERÁ TRUE, OU SEJA, A CONTA ESTÁ VÁLIDA, NÃO ESTÁ EXPIRADA.
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		
		// AQUI VOCÊ ESTÁ DIZENDO: SEMPRE QUE PERGUNTAREM SE A CONTA NÃO ESTÁ BLOQUEADA,
	    // A RESPOSTA SERÁ TRUE, OU SEJA, A CONTA NÃO ESTÁ BLOQUEADA E O USUÁRIO PODE ACESSAR.
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		
		// DIZ QUE A (CREDENCIAL) SENHA DO USUÁRIO AINDA ESTÁ VALIDA (NÃO EXPIROU)
		return true;
	}

	@Override
	public boolean isEnabled() {
		
		// DIZ QUE A CONTA DO USUÁRIO ESTÁ ATIVA, OU SEJA, ELE TEM PERMISSÃO PARA ENTRAR NO SISTEMA
		// MAS ISSO NÃO SIGNIFICA QUE ELE JÁ ESTÁ LOGADO, APENAS QUE PODE FAZER LOGIN
		return true;
	}
	
	
	
	
	
	
	  
	 // RESUMO: ESTA CLASSE LIGA O USUÁRIO AO SPRING SECURITY.  
   // ELA GUARDA LOGIN, SENHA E PERMISSÕES DO USUÁRIO, 
   // E AJUDA O SPRING A FAZER O LOGIN E CHECAR SE A CONTA ESTÁ ATIVA.


}